<?php

/**
 * @file
 * Defines shipping methods for Circa Desserts.
 */


/**
 * Implements hook_commerce_shipping_method_info().
 */
function commerce_shipping_example_commerce_shipping_method_info() {
  $shipping_methods = array();

  $shipping_methods['example_shipping_method'] = array(
    'title' => t('Example shipping method'),
    'description' => t('Defines a single flat rate service with a couple of service details.'),
  );

  return $shipping_methods;
}

/**
 * Implements hook_commerce_shipping_service_info().
 */
function commerce_shipping_example_commerce_shipping_service_info() {
  $shipping_services = array();

  $shipping_services['example_shipping_service'] = array(
    'title' => t('Example shipping service'),
    'description' => t('A $20 flat rate service with express delivery available for an additional $15.'),
    'display_title' => t('Shipping'),
    'shipping_method' => 'example_shipping_method',
    'price_component' => 'shipping',
    'callbacks' => array(
      'rate' => 'commerce_shipping_example_service_rate',
      'details_form' => 'commerce_shipping_example_service_details_form',
      'details_form_validate' => 'commerce_shipping_example_service_details_form_validate',
      'details_form_submit' => 'commerce_shipping_example_service_details_form_submit',
    ),
  );

  return $shipping_services;
}

/**
 * Shipping service callback: returns a base price array for a shipping service
 * calculated for the given order.
 */
function commerce_shipping_example_service_rate($shipping_service, $order) {
  return array(
    'amount' => 2000,
    'currency_code' => 'USD',
    'data' => array(),
  );
}

/**
 * Shipping service callback: returns the example shipping service details form.
 */
function commerce_shipping_example_service_details_form($pane_form, $pane_values, $checkout_pane, $order, $shipping_service) {
  $form = array();

  $pane_values['service_details'] += array(
    'name' => '',
    'express' => '',
  );

  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),
    '#description' => t('This is a demonstration field coded to fail validation for single character values.'),
    '#default_value' => $pane_values['service_details']['name'],
    '#required' => TRUE,
  );

  $form['express'] = array(
    '#type' => 'checkbox',
    '#title' => t('Express delivery'),
    '#description' => t('Express delivery (costs an additional $15)'),
    '#default_value' => $pane_values['service_details']['express'],
  );

  return $form;
}

/**
 * Shipping service callback: validates the example shipping service details.
 */
function commerce_shipping_example_service_details_form_validate($details_form, $details_values, $shipping_service, $order, $form_parents) {
  if (strlen($details_values['name']) < 2) {
    form_set_error(implode('][', array_merge($form_parents, array('name'))), t('You must enter a name two or more characters long.'));

    // Even though the form error is enough to stop the submission of the form,
    // it's not enough to stop it from a Commerce standpoint because of the
    // combined validation / submission going on per-pane in the checkout form.
    return FALSE;
  }
}

/**
 * Shipping service callback: increases the shipping line item's unit price if
 * express delivery was selected.
 */
function commerce_shipping_example_service_details_form_submit($details_form, $details_values, $line_item) {
  if ($details_values['express']) {
    $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);

    // Build a price array for the express delivery fee.
    $express_price = array(
      'amount' => 1500,
      'currency_code' => 'USD',
      'data' => array(),
    );

    // Multiply the unit price by 2.
    $line_item_wrapper->commerce_unit_price->amount += 1500;

    // Add the express delivery fee component to the unit price.
    $line_item_wrapper->commerce_unit_price->data = commerce_price_component_add(
      $line_item_wrapper->commerce_unit_price->value(),
      'example_shipping_service_express',
      $express_price,
      TRUE,
      FALSE
    );
  }
}

/**
 * Implements hook_commerce_price_component_type_info().
 */
function commerce_shipping_example_commerce_price_component_type_info() {
  return array(
    'example_shipping_service_express' => array(
      'title' => t('Express delivery'),
      'weight' => 20,
    ),
  );
}





/******Druplus**************/


<?php

/**
 * @file
 * Adds an engravable product line item type that we use for piPod touch and a
 * simple flat rate shipping method with services tailored to this site.
 */


/**
 * Implements hook_commerce_line_item_type_info().
 */
function druplus_commerce_line_item_type_info() {
  return array(
    'product_engravable' => array(
      'name' => t('Engravable product'),
      'description' => t('References a product and displays it with the SKU as the label, allowing the customer to add an engraving.'),
      'product' => TRUE,
      'add_form_submit_value' => t('Add product'),
      'base' => 'commerce_product_line_item',
    ),
  );
}

/**
 * Implements hook_commerce_shipping_method_info().
 */
function druplus_commerce_shipping_method_info() {
  $shipping_methods = array();

  $shipping_methods['druplus_shipping'] = array(
    'title' => t('Flat rate shipping'),
    'description' => t('Defines a couple of flat rate services.'),
  );

  return $shipping_methods;
}

/**
 * Implements hook_commerce_shipping_service_info().
 */
function druplus_commerce_shipping_service_info() {
  $shipping_services = array();

  $shipping_services['druplus_free_shipping'] = array(
    'title' => t('Free shipping'),
    'description' => t('Free shipping for orders over $50.'),
    'shipping_method' => 'druplus_shipping',
    'price_component' => 'shipping',
    'callbacks' => array(
      'rate' => 'druplus_shipping_service_rate',
    ),
  );

  $shipping_services['druplus_standard_shipping'] = array(
    'title' => t('Standard shipping'),
    'description' => t('Standard shipping at normal ground delivery speed.'),
    'shipping_method' => 'druplus_shipping',
    'price_component' => 'shipping',
    'callbacks' => array(
      'rate' => 'druplus_shipping_service_rate',
    ),
  );

  $shipping_services['druplus_expedited_shipping'] = array(
    'title' => t('Expedited shipping'),
    'description' => t('Faster shipping for those willing to pay.'),
    'shipping_method' => 'druplus_shipping',
    'price_component' => 'shipping',
    'callbacks' => array(
      'rate' => 'druplus_shipping_service_rate',
    ),
  );

  return $shipping_services;
}

/**
 * Shipping service callback: returns a base price array for a shipping service
 * calculated for the given order.
 */
function druplus_shipping_service_rate($shipping_service, $order) {
  switch ($shipping_service['name']) {
    case 'druplus_standard_shipping':
      $amount = 3000;
      break;

    case 'druplus_expedited_shipping':
      $amount = 6500;
      break;

    default:
     $amount = 0;
  }

  return array(
    'amount' => $amount,
    'currency_code' => 'USD',
    'data' => array(),
  );
}
